module.exports = {
  IS_REQUIRED: 'IS_REQUIRED',
  SHOULD_BE_A_STRING: 'SHOULD_BE_A_STRING',
  SHOULD_BE_A_NUMBER: 'SHOULD_BE_A_NUMBER',
  LENGTH_TOO_LONG: 'LENGTH_TOO_LONG',
  LENGTH_TOO_SHORT: 'LENGTH_TOO_SHORT',
  SHOULD_BE_GREATER: 'SHOULD_BE_GREATER',
  SHOULD_BE_SMALLER: 'SHOULD_BE_SMALLER',
};
